name: "baker build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: baker

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: golangci-lint cache
        uses: actions/cache@v4
        with:
          path: /tmp/.cache-golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('.golangci.yml') }}-main

      - name: go mod cache
        uses: actions/cache@v4
        with:
          path: /tmp/.go-pkg-mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}-main

      - name: go build cache
        uses: actions/cache@v4
        with:
          path: /tmp/.cache-go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-main

      - name: inject cache folders into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "/tmp/.cache-golangci-lint": "/root/.cache/golangci-lint",
              "/tmp/.go-pkg-mod": "/go/pkg/mod",
              "/tmp/.cache-go-build": "/root/.cache/go-build"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: inject docker cache into docker
        run: |
          mkdir -p /tmp/.docker-cache
          if [ -f /tmp/.docker-cache/postgres.tar ]; then
            docker load -i /tmp/.docker-cache/postgres.tar
          fi
          if [ -f /tmp/.docker-cache/golang.tar ]; then
            docker load -i /tmp/.docker-cache/golang.tar
          fi

      - name: prepare test environment
        run: |
          docker compose up -d postgres
          GATEWAY_IP=$(docker inspect $(docker compose ps --format json | jq -r '.Name') | jq -r '.[].NetworkSettings.Networks.baker_default.Gateway')
          echo "DATABASE_URL=postgres://user:password@$GATEWAY_IP:2345/database" >> $GITHUB_ENV

      - name: Pull cache before build
        run: docker pull lopezator/baker:cache || true

      - name: docker bake build
        uses: docker/bake-action@v5
        with:
          targets: prepare
          push: true

      - name: docker bake push release
        if: github.ref == 'refs/heads/main'
        uses: docker/bake-action@v5
        with:
          targets: release
          push: true