name: "cache-test build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build image
        uses: docker/bake-action@v5
        with:
          targets: build
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: release image
        if: github.ref == 'refs/heads/main'
        uses: docker/bake-action@v5
        with:
          targets: release
          push: true