name: "cache-test build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CACHE: invalidate-cache-18
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: cache-test

      - name: golangci-lint cache
        uses: actions/cache@v4
        id: golangci-lint-cache-restore
        with:
          path: cache-golangci-lint
          key: ${{ runner.os }}-${{ hashFiles('.go-builder/.golangci.yml') }}-main

      - name: go mod cache
        uses: actions/cache@v4
        id: go-mod-cache-restore
        with:
          path: go-pkg-mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}-main

      - name: go build cache
        uses: actions/cache@v4
        id: go-build-cache-restore
        with:
          path: cache-go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-main

      - name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-map: |
            {
              "cache-golangci-lint": "/root/.cache/golangci-lint",
              "go-pkg-mod": "/go/pkg/mod",
              "cache-go-build": "/root/.cache/go-build"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: base
        run: docker buildx bake --file docker-compose-cache.json base

      - name: prepare
        run: docker buildx bake --file docker-compose-cache.json prepare

      - name: sanity-check
        run: docker buildx bake --file docker-compose-cache.json sanity-check

      - name: build
        run: |
          make APP=${{ env.APP }} VERSION_NOPREFIX=${{ env.VERSION_NOPREFIX }}
          docker buildx bake --file docker-compose-cache.json build

      - name: release
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx bake --file docker-compose-cache.json runtime
          make PREFIX=${{ env.PREFIX }} NAME=${{ env.NAME }} VERSION=${{ env.VERSION }}
          docker push ${{ env.PREFIX }}/${{ env.NAME }}:${{ env.VERSION }}