name: "cache-test build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CACHE: invalidate-cache-18
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: cache-test

      - name: restore golangci-lint cache
        uses: actions/cache/restore@v4
        id: golangci-lint-cache-restore
        with:
          path: cache-golangci-lint
          key: ${{ runner.os }}-${{ hashFiles('.go-builder/.golangci.yml') }}-main  # Always restore from main cache
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('.go-builder/.golangci.yml') }}-
            ${{ runner.os }}-

      - name: restore go mod cache
        uses: actions/cache/restore@v4
        id: go-mod-cache-restore
        with:
          path: go-pkg-mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}-main  # Always restore from main cache
          restore-keys: |
            ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-mod-

      - name: restore go build cache
        uses: actions/cache/restore@v4
        id: go-build-cache-restore
        with:
          path: cache-go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-main  # Always restore from main cache
          restore-keys: |
            ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-build-

      - name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "cache-golangci-lint": "/root/.cache/golangci-lint",
              "go-pkg-mod": "/go/pkg/mod",
              "cache-go-build": "/root/.cache/go-build"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: prepare
        run: docker buildx build -f Dockerfile.build --target prepare --cache-from=type=gha --cache-to=type=gha,mode=max .

      - name: sanity-check
        run: docker buildx build -f Dockerfile.build --target sanity-check --cache-from=type=gha --cache-to=type=gha,mode=max .

      - name: build
        run: docker buildx build -f Dockerfile.build --target build --cache-from=type=gha --cache-to=type=gha,mode=max .

      - name: save golangci-lint cache
        uses: actions/cache/save@v4
        with:
          path: cache-golangci-lint
          key: ${{ runner.os }}-${{ hashFiles('.go-builder/.golangci.yml') }}-${{ github.sha }}
        if: github.ref == 'refs/heads/main'

      - name: save go mod cache
        uses: actions/cache/save@v4
        with:
          path: go-pkg-mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
        if: github.ref == 'refs/heads/main'

      - name: save go build cache
        uses: actions/cache/save@v4
        with:
          path: cache-go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
        if: github.ref == 'refs/heads/main'

      - name: release
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runtime
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
